# -*- coding: utf-8 -*-
"""PredictorMercado_Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rr05ukk7jECB7DSTrONYjrCSRCkrOvNM
"""

# =============================================================================
# PREDICTOR DEL MERCADO ELÉCTRICO ESPAÑOL
# Herramienta de optimización de consumo industrial
# -----------------------------------------------------------------------------
# Objetivo: Predecir la curva horaria de precios del día siguiente (€/MWh)
# y recomendar las franjas óptimas de consumo para industria.
#
# Fuentes de datos:
#   - Precios OMIE: API pública de Red Eléctrica de España (REE)
#   - Meteorología: Open-Meteo Archive & Forecast API
#
# Modelo: XGBoost con variables climáticas, calendario y demanda nacional
# =============================================================================

# ── DEPENDENCIAS ──────────────────────────────────────────────────────────────
# pip install requests pandas numpy scikit-learn xgboost matplotlib seaborn joblib python-dateutil

import requests
import pandas as pd
import numpy as np
import time
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

# ── CONFIGURACIÓN GLOBAL ──────────────────────────────────────────────────────
AÑOS_HISTORICO = 3          # Años de datos históricos a descargar
MODELO_PATH    = "modelo_mercado_electrico.pkl"
FEATURES_PATH  = "features_mercado_electrico.pkl"

# Coordenadas estratégicas para capturar la generación renovable nacional:
#   Galicia   → eólica del norte
#   Zaragoza  → valle del Ebro (eólica + solar interior)
#   Sevilla   → solar del sur
CIUDADES = {
    'Galicia':   {'lat': 43.37, 'lon': -8.39},
    'Zaragoza':  {'lat': 41.65, 'lon': -0.88},
    'Andalucia': {'lat': 37.38, 'lon': -5.98},
}

# =============================================================================
# BLOQUE 1 — DESCARGA DE DATOS HISTÓRICOS
# =============================================================================

def descargar_precios_ree(años: int = 3) -> pd.DataFrame:
    """
    Descarga precios horarios del mercado OMIE desde la API de REE.
    Devuelve un DataFrame con índice datetime y columna 'Precio' (€/MWh).
    """
    url = "https://apidatos.ree.es/es/datos/mercados/precios-mercados-tiempo-real"
    datos = []
    fecha_inicio = datetime.now() - relativedelta(years=años)
    fecha_inicio = fecha_inicio.replace(day=1, hour=0, minute=0, second=0)
    meses_total = años * 12

    print(f"⚡ Descargando {meses_total} meses de precios REE...")
    for i in range(meses_total):
        inicio = fecha_inicio + relativedelta(months=i)
        fin    = fecha_inicio + relativedelta(months=i+1) - relativedelta(minutes=1)

        params = {
            'start_date': inicio.strftime('%Y-%m-%dT%H:%M'),
            'end_date':   fin.strftime('%Y-%m-%dT%H:%M'),
            'time_trunc': 'hour'
        }
        try:
            r = requests.get(url, params=params,
                             headers={'Accept': 'application/json'}, timeout=15)
            if r.status_code == 200:
                for v in r.json()['included'][0]['attributes']['values']:
                    datos.append({'Fecha': v['datetime'], 'Precio': v['value']})
        except Exception as e:
            print(f"  ⚠️  Error mes {i}: {e}")
        time.sleep(0.4)

    df = pd.DataFrame(datos)
    df['Fecha'] = pd.to_datetime(df['Fecha'], utc=True)
    df = df.set_index('Fecha')
    df.index = df.index.tz_convert('Europe/Madrid').tz_localize(None)
    df = df[~df.index.duplicated(keep='first')].sort_index()
    print(f"  ✅ {len(df):,} horas descargadas")
    return df


def descargar_demanda_ree(años: int = 3) -> pd.DataFrame:
    """
    Descarga demanda horaria real desde la API de REE.
    Devuelve un DataFrame con columna 'Demanda' (MWh).
    """
    url = "https://apidatos.ree.es/es/datos/demanda/demanda-tiempo-real"
    datos = []
    fecha_inicio = datetime.now() - relativedelta(years=años)
    fecha_inicio = fecha_inicio.replace(day=1, hour=0, minute=0, second=0)
    meses_total = años * 12

    print(f"🔌 Descargando {meses_total} meses de demanda REE...")
    for i in range(meses_total):
        inicio = fecha_inicio + relativedelta(months=i)
        fin    = fecha_inicio + relativedelta(months=i+1) - relativedelta(minutes=1)

        params = {
            'start_date': inicio.strftime('%Y-%m-%dT%H:%M'),
            'end_date':   fin.strftime('%Y-%m-%dT%H:%M'),
            'time_trunc': 'hour'
        }
        try:
            r = requests.get(url, params=params,
                             headers={'Accept': 'application/json'}, timeout=15)
            if r.status_code == 200:
                for curva in r.json().get('included', []):
                    if 'real' in curva.get('type', '').lower():
                        for v in curva['attributes']['values']:
                            datos.append({'Fecha': v['datetime'], 'Demanda': v['value']})
                        break
        except Exception as e:
            print(f"  ⚠️  Error mes {i}: {e}")
        time.sleep(0.4)

    df = pd.DataFrame(datos)
    df['Fecha'] = pd.to_datetime(df['Fecha'], utc=True)
    df = df.set_index('Fecha')
    df.index = df.index.tz_convert('Europe/Madrid').tz_localize(None)
    df = df[~df.index.duplicated(keep='first')].sort_index()
    print(f"  ✅ {len(df):,} horas de demanda descargadas")
    return df


def descargar_clima_historico(ciudades: dict, años: int = 3) -> pd.DataFrame:
    """
    Descarga datos meteorológicos horarios históricos desde Open-Meteo Archive.
    Devuelve un DataFrame con temperatura, radiación y viento por ciudad.
    """
    url = "https://archive-api.open-meteo.com/v1/archive"
    fecha_fin   = datetime.now().strftime('%Y-%m-%d')
    fecha_inicio = (datetime.now() - relativedelta(years=años)).strftime('%Y-%m-%d')

    lats = ",".join(str(c['lat']) for c in ciudades.values())
    lons = ",".join(str(c['lon']) for c in ciudades.values())

    print(f"🌤️  Descargando clima histórico ({fecha_inicio} → {fecha_fin})...")
    params = {
        "latitude":  lats,
        "longitude": lons,
        "start_date": fecha_inicio,
        "end_date":   fecha_fin,
        "hourly": ["temperature_2m", "shortwave_radiation", "wind_speed_10m"],
        "timezone": "Europe/Madrid"
    }
    r = requests.get(url, params=params, timeout=60).json()

    dfs = []
    for i, ciudad in enumerate(ciudades.keys()):
        df_c = pd.DataFrame({
            'Fecha':               pd.to_datetime(r[i]['hourly']['time']),
            f'Temp_{ciudad}':      r[i]['hourly']['temperature_2m'],
            f'Radiacion_{ciudad}': r[i]['hourly']['shortwave_radiation'],
            f'Viento_{ciudad}':    r[i]['hourly']['wind_speed_10m'],
        }).set_index('Fecha')
        dfs.append(df_c)

    df_clima = pd.concat(dfs, axis=1)
    print(f"  ✅ {len(df_clima):,} horas de clima descargadas")
    return df_clima


def construir_dataset(años: int = 3) -> pd.DataFrame:
    """
    Descarga y une precios, demanda y clima en un único DataFrame limpio.
    """
    print("\n" + "="*60)
    print("FASE 1: CONSTRUCCIÓN DEL DATASET HISTÓRICO")
    print("="*60)

    df_precios = descargar_precios_ree(años)
    df_demanda = descargar_demanda_ree(años)
    df_clima   = descargar_clima_historico(CIUDADES, años)

    df = df_precios.join(df_demanda, how='inner').join(df_clima, how='inner')
    df.dropna(inplace=True)

    print(f"\n  📊 Dataset final: {len(df):,} horas | {df.shape[1]} variables")
    return df


# =============================================================================
# BLOQUE 2 — INGENIERÍA DE VARIABLES
# =============================================================================

def crear_features(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.Series]:
    """
    Construye las variables de entrada (X) y el objetivo (y).

    Variables incluidas:
      - Clima en 3 zonas estratégicas (temperatura, radiación solar, viento)
      - Demanda nacional horaria
      - Calendario: hora, día semana, mes, fin de semana
      - Lags de precio: precio de hace 1h, 24h (mismo slot ayer) y 168h (semana)
      - Media móvil del precio en las últimas 24h
    """
    df = df.copy().sort_index()

    # Variables de calendario
    df['Hora']          = df.index.hour
    df['Dia_Semana']    = df.index.dayofweek
    df['Mes']           = df.index.month
    df['Es_FinDeSemana'] = (df['Dia_Semana'] >= 5).astype(int)

    # Lags de precio — el mercado tiene fuerte inercia
    df['Precio_Lag_1h']   = df['Precio'].shift(1)    # hace 1 hora
    df['Precio_Lag_24h']  = df['Precio'].shift(24)   # mismo slot ayer
    df['Precio_Lag_168h'] = df['Precio'].shift(168)  # mismo slot semana pasada
    df['Precio_MA_24h']   = df['Precio'].shift(1).rolling(24).mean()  # tendencia reciente

    df.dropna(inplace=True)

    feature_cols = [c for c in df.columns if c != 'Precio']
    return df[feature_cols], df['Precio']


# =============================================================================
# BLOQUE 3 — ENTRENAMIENTO Y EVALUACIÓN
# =============================================================================

def entrenar_modelo(X: pd.DataFrame, y: pd.Series) -> tuple:
    """
    Entrena un XGBoost con split cronológico (80/20).
    Devuelve el modelo, métricas y datos de test.
    """
    print("\n" + "="*60)
    print("FASE 2: ENTRENAMIENTO DEL MODELO")
    print("="*60)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, shuffle=False  # Respetamos el tiempo — sin data leakage
    )

    modelo = xgb.XGBRegressor(
        n_estimators=400,
        max_depth=7,
        learning_rate=0.04,
        subsample=0.85,
        colsample_bytree=0.85,
        min_child_weight=3,
        random_state=42,
        n_jobs=-1
    )

    print("  🧠 Entrenando XGBoost...")
    modelo.fit(X_train, y_train,
               eval_set=[(X_test, y_test)],
               verbose=False)

    pred = modelo.predict(X_test)
    mae  = mean_absolute_error(y_test, pred)
    r2   = r2_score(y_test, pred)

    print(f"\n  📈 Resultados en test (últimas {len(y_test):,} horas):")
    print(f"     MAE  → {mae:.2f} €/MWh de error medio")
    print(f"     R²   → {r2*100:.1f}% de varianza explicada")

    return modelo, pred, y_test, mae, r2


def visualizar_resultados(y_test, pred, modelo, X, mae, r2):
    """Genera las 3 gráficas clave del análisis."""

    fig, axes = plt.subplots(3, 1, figsize=(14, 16))
    fig.suptitle('Predictor del Mercado Eléctrico Español', fontsize=16, fontweight='bold', y=0.98)

    # ── Gráfica 1: Predicción vs Realidad (últimas 72h) ──
    n = 72
    ax1 = axes[0]
    ax1.plot(y_test.index[-n:], y_test.values[-n:],
             color='black', linewidth=2, marker='o', markersize=3, label='Precio REAL (OMIE)')
    ax1.plot(y_test.index[-n:], pred[-n:],
             color='#E74C3C', linewidth=2, linestyle='--', marker='x', markersize=3,
             label=f'Predicción IA (MAE={mae:.1f} €/MWh)')
    ax1.set_title('Últimas 72 horas', fontweight='bold')
    ax1.set_ylabel('Precio €/MWh')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # ── Gráfica 2: Importancia de variables ──
    ax2 = axes[1]
    importancias = pd.Series(modelo.feature_importances_, index=X.columns).sort_values()
    colores = ['#E74C3C' if 'Lag' in i or 'MA' in i
               else '#3498DB' if 'Demanda' in i
               else '#2ECC71' if any(c in i for c in ['Galicia', 'Zaragoza', 'Andalucia'])
               else '#95A5A6' for i in importancias.index]
    importancias.plot(kind='barh', ax=ax2, color=colores)
    ax2.set_title('¿Qué explica el precio de la luz?', fontweight='bold')
    ax2.set_xlabel('Importancia relativa')

    # Leyenda manual
    from matplotlib.patches import Patch
    leyenda = [
        Patch(color='#E74C3C', label='Memoria de precio (lags)'),
        Patch(color='#3498DB', label='Demanda nacional'),
        Patch(color='#2ECC71', label='Clima (viento/sol)'),
        Patch(color='#95A5A6', label='Calendario'),
    ]
    ax2.legend(handles=leyenda, loc='lower right', fontsize=9)
    ax2.grid(True, alpha=0.3, axis='x')

    # ── Gráfica 3: Perfil típico por hora (qué horas son más baratas) ──
    ax3 = axes[2]
    df_plot = pd.DataFrame({'Precio': y_test.values, 'Hora': y_test.index.hour})
    perfil = df_plot.groupby('Hora')['Precio'].agg(['mean', 'std'])
    ax3.fill_between(perfil.index,
                     perfil['mean'] - perfil['std'],
                     perfil['mean'] + perfil['std'],
                     alpha=0.2, color='#3498DB')
    ax3.plot(perfil.index, perfil['mean'], color='#3498DB', linewidth=2.5, marker='o')
    ax3.axvspan(0, 7, alpha=0.08, color='green', label='Valle (0-7h)')
    ax3.axvspan(10, 14, alpha=0.08, color='red', label='Pico mediodía (10-14h)')
    ax3.axvspan(18, 22, alpha=0.08, color='orange', label='Pico tarde (18-22h)')
    ax3.set_title('Perfil Horario Típico del Precio', fontweight='bold')
    ax3.set_ylabel('Precio medio €/MWh')
    ax3.set_xlabel('Hora del día')
    ax3.set_xticks(range(24))
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('resultados_mercado_electrico.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("\n  💾 Gráficas guardadas en: resultados_mercado_electrico.png")


# =============================================================================
# BLOQUE 4 — PREDICCIÓN DEL DÍA SIGUIENTE
# =============================================================================

def predecir_manana(modelo, feature_cols: list, df_historico: pd.DataFrame) -> pd.DataFrame:
    """
    Predice la curva horaria de precios del día siguiente.
    Requiere el historial reciente para calcular los lags de precio.
    """
    print("\n" + "="*60)
    print("FASE 3: PREDICCIÓN PARA MAÑANA")
    print("="*60)

    manana = datetime.now() + timedelta(days=1)
    fecha_str = manana.strftime('%Y-%m-%d')
    print(f"  📅 Calculando curva para: {fecha_str}")

    # Descargamos previsión meteorológica de mañana
    url_fc = "https://api.open-meteo.com/v1/forecast"
    lats = ",".join(str(c['lat']) for c in CIUDADES.values())
    lons = ",".join(str(c['lon']) for c in CIUDADES.values())

    params_fc = {
        "latitude": lats, "longitude": lons,
        "start_date": fecha_str, "end_date": fecha_str,
        "hourly": ["temperature_2m", "shortwave_radiation", "wind_speed_10m"],
        "timezone": "Europe/Madrid"
    }
    r = requests.get(url_fc, params=params_fc, timeout=30).json()

    horas = pd.to_datetime(r[0]['hourly']['time'])
    df_fc = pd.DataFrame(index=horas)

    for i, ciudad in enumerate(CIUDADES.keys()):
        df_fc[f'Temp_{ciudad}']      = r[i]['hourly']['temperature_2m']
        df_fc[f'Radiacion_{ciudad}'] = r[i]['hourly']['shortwave_radiation']
        df_fc[f'Viento_{ciudad}']    = r[i]['hourly']['wind_speed_10m']

    # Intentamos descargar demanda prevista de REE para mañana
    try:
        url_dem = "https://apidatos.ree.es/es/datos/demanda/demanda-tiempo-real"
        params_dem = {
            'start_date': manana.strftime('%Y-%m-%dT00:00'),
            'end_date':   manana.strftime('%Y-%m-%dT23:59'),
            'time_trunc': 'hour'
        }
        r_dem = requests.get(url_dem, params=params_dem,
                             headers={'Accept': 'application/json'}, timeout=15).json()
        demanda_vals = []
        for curva in r_dem.get('included', []):
            if any(k in curva.get('type', '').lower() for k in ['prevista', 'programada', 'real']):
                demanda_vals = [v['value'] for v in curva['attributes']['values']]
                break
        if demanda_vals:
            df_fc['Demanda'] = demanda_vals[:24]
        else:
            # Fallback: usamos la media de la misma hora en días recientes
            df_fc['Demanda'] = df_historico['Demanda'].groupby(
                df_historico.index.hour).mean().values
    except:
        df_fc['Demanda'] = df_historico['Demanda'].groupby(
            df_historico.index.hour).mean().values

    # Calendario
    df_fc['Hora']           = df_fc.index.hour
    df_fc['Dia_Semana']     = manana.weekday()
    df_fc['Mes']            = manana.month
    df_fc['Es_FinDeSemana'] = int(manana.weekday() >= 5)

    # Lags de precio usando el historial reciente
    precios_recientes = df_historico['Precio'].sort_index().tail(200)
    df_fc['Precio_Lag_1h']   = precios_recientes.iloc[-1]   # última hora conocida
    df_fc['Precio_Lag_24h']  = precios_recientes.iloc[-24:].values if len(precios_recientes) >= 24 else precios_recientes.mean()
    df_fc['Precio_Lag_168h'] = precios_recientes.iloc[-168:-(168-24)].values if len(precios_recientes) >= 168 else precios_recientes.mean()
    df_fc['Precio_MA_24h']   = precios_recientes.iloc[-24:].mean()

    # Predicción
    df_fc = df_fc[feature_cols]
    precios_pred = modelo.predict(df_fc)
    df_fc['Precio_Predicho'] = precios_pred

    return df_fc


def panel_industrial(df_pred: pd.DataFrame):
    """
    Genera el panel de recomendación para optimización de consumo industrial.
    Identifica las 6 horas más baratas y las 6 más caras del día siguiente.
    """
    precios = df_pred['Precio_Predicho']
    precio_medio = precios.mean()

    horas_baratas = precios.nsmallest(6).index
    horas_caras   = precios.nlargest(6).index

    print("\n" + "="*60)
    print("PANEL DE OPTIMIZACIÓN INDUSTRIAL")
    print("="*60)
    print(f"  📊 Precio medio estimado mañana: {precio_medio:.1f} €/MWh")
    print(f"\n  ✅ ENCENDER MÁQUINAS (horas más baratas):")
    for h in sorted(horas_baratas):
        print(f"     {h.strftime('%H:%M')} → {precios[h]:.1f} €/MWh")
    print(f"\n  ❌ APAGAR MÁQUINAS (horas más caras):")
    for h in sorted(horas_caras):
        print(f"     {h.strftime('%H:%M')} → {precios[h]:.1f} €/MWh")

    ahorro_potencial = precios.nlargest(6).mean() - precios.nsmallest(6).mean()
    print(f"\n  💰 Diferencial precio pico/valle: {ahorro_potencial:.1f} €/MWh")

    # Gráfica del panel
    fig, ax = plt.subplots(figsize=(13, 6))
    colores = ['#E74C3C' if h in horas_caras
               else '#2ECC71' if h in horas_baratas
               else '#BDC3C7' for h in precios.index]

    ax.bar(precios.index.hour, precios.values, color=colores, edgecolor='white', linewidth=0.5)
    ax.axhline(precio_medio, color='#2C3E50', linewidth=1.5, linestyle='--',
               label=f'Precio medio: {precio_medio:.1f} €/MWh')
    ax.set_title(f"Panel de Control Industrial — {df_pred.index[0].strftime('%d/%m/%Y')}",
                 fontsize=14, fontweight='bold')
    ax.set_xlabel('Hora del día', fontsize=12)
    ax.set_ylabel('Precio estimado €/MWh', fontsize=12)
    ax.set_xticks(range(24))

    from matplotlib.patches import Patch
    leyenda = [
        Patch(color='#2ECC71', label='Encender máquinas (más barato)'),
        Patch(color='#E74C3C', label='Apagar máquinas (más caro)'),
        Patch(color='#BDC3C7', label='Horas intermedias'),
    ]
    ax.legend(handles=leyenda, loc='upper left')
    ax.grid(True, alpha=0.3, axis='y')

    plt.tight_layout()
    plt.savefig('panel_industrial_manana.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("  💾 Panel guardado en: panel_industrial_manana.png")


# =============================================================================
# EJECUCIÓN PRINCIPAL
# =============================================================================

if __name__ == "__main__":

    print("\n" + "🔋 "*20)
    print("PREDICTOR DEL MERCADO ELÉCTRICO ESPAÑOL")
    print("Optimización de consumo industrial")
    print("🔋 "*20 + "\n")

    # ── 1. Construir dataset ──────────────────────────────────────────────────
    df = construir_dataset(años=AÑOS_HISTORICO)

    # ── 2. Crear features y entrenar ─────────────────────────────────────────
    X, y = crear_features(df)
    modelo, pred, y_test, mae, r2 = entrenar_modelo(X, y)

    # ── 3. Visualizar resultados ──────────────────────────────────────────────
    visualizar_resultados(y_test, pred, modelo, X, mae, r2)

    # ── 4. Guardar modelo ─────────────────────────────────────────────────────
    joblib.dump(modelo, MODELO_PATH)
    joblib.dump(list(X.columns), FEATURES_PATH)
    print(f"\n  💾 Modelo guardado en: {MODELO_PATH}")
    print(f"  💾 Features guardadas en: {FEATURES_PATH}")

    # ── 5. Predicción día siguiente + panel industrial ────────────────────────
    df_pred = predecir_manana(modelo, list(X.columns), df)
    panel_industrial(df_pred)

    print("\n✅ ANÁLISIS COMPLETO")
    print("   Archivos generados:")
    print(f"   - {MODELO_PATH}")
    print(f"   - {FEATURES_PATH}")
    print("   - resultados_mercado_electrico.png")
    print("   - panel_industrial_manana.png")
